
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int MENOS = 4;
  public static final int RPAREN = 8;
  public static final int SEMI = 2;
  public static final int SERIE = 24;
  public static final int O = 17;
  public static final int LPAREN = 7;
  public static final int ID = 13;
  public static final int VIRGULA = 20;
  public static final int RESOLVA = 19;
  public static final int ATRIB = 14;
  public static final int DOBRO = 18;
  public static final int MAIS = 3;
  public static final int RCOL = 10;
  public static final int EOF = 0;
  public static final int MENOSUNIT = 6;
  public static final int QUAL = 15;
  public static final int LCOL = 9;
  public static final int ELEMENTO = 22;
  public static final int TERCEIRO = 21;
  public static final int NUMERO = 26;
  public static final int error = 1;
  public static final int DA = 23;
  public static final int SE = 25;
  public static final int VEZES = 5;
  public static final int RSER = 12;
  public static final int EH = 16;
  public static final int LSER = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "MAIS",
  "MENOS",
  "VEZES",
  "MENOSUNIT",
  "LPAREN",
  "RPAREN",
  "LCOL",
  "RCOL",
  "LSER",
  "RSER",
  "ID",
  "ATRIB",
  "QUAL",
  "EH",
  "O",
  "DOBRO",
  "RESOLVA",
  "VIRGULA",
  "TERCEIRO",
  "ELEMENTO",
  "DA",
  "SERIE",
  "SE",
  "NUMERO"
  };
}

